export type AssessmentDomain = "vocabulary" | "grammar" | "communication" | "process" | "risk" | "negotiation";
export type AssessmentQuestion = {
  id: string;
  track: "english" | "trade";
  level: number;
  domain: AssessmentDomain;
  zh: string;
  en: string;
  optionsZh: string[];
  optionsEn: string[];
  answer: number;
};

const e = (id: string, level: number, domain: AssessmentDomain, zh: string, en: string, optionsZh: string[], optionsEn: string[], answer: number): AssessmentQuestion => ({ id, track: "english", level, domain, zh, en, optionsZh, optionsEn, answer });
const t = (id: string, level: number, domain: AssessmentDomain, zh: string, en: string, optionsZh: string[], optionsEn: string[], answer: number): AssessmentQuestion => ({ id, track: "trade", level, domain, zh, en, optionsZh, optionsEn, answer });

export const assessmentQuestions: AssessmentQuestion[] = [
  e("e01",1,"vocabulary","quotation 最接近哪个意思？","What does quotation mean?",["报价单","装箱单","提单","保单"],["price offer","packing list","bill of lading","insurance policy"],0),
  e("e02",1,"grammar","选择正确句子：我们昨天收到了询盘。","Choose the correct sentence.",["We receive the inquiry yesterday.","We received the inquiry yesterday.","We have receive the inquiry yesterday.","We receiving the inquiry yesterday."],["We receive the inquiry yesterday.","We received the inquiry yesterday.","We have receive the inquiry yesterday.","We receiving the inquiry yesterday."],1),
  e("e03",2,"communication","哪句话适合礼貌索取产品目录？","Which sentence politely asks for a catalogue?",["Send catalogue.","Could you please send us your latest catalogue?","I want catalogue now.","Catalogue?"],["Send catalogue.","Could you please send us your latest catalogue?","I want catalogue now.","Catalogue?"],1),
  e("e04",2,"vocabulary","lead time 在订单沟通中指什么？","What does lead time mean?",["付款期限","生产到交付所需时间","产品寿命","会议时长"],["payment period","time from production to delivery","product lifetime","meeting duration"],1),
  e("e05",2,"grammar","选择正确条件句。","Choose the correct conditional sentence.",["If you increase the quantity, we can offer a better price.","If you will increase quantity, we offer better price.","If quantity increased, we can offering.","If you increase, we offered."],["If you increase the quantity, we can offer a better price.","If you will increase quantity, we offer better price.","If quantity increased, we can offering.","If you increase, we offered."],0),
  e("e06",3,"communication","客户没有回复报价，哪句跟进最自然？","Which is the best quotation follow-up?",["Why no reply?","Just checking whether you had a chance to review our quotation.","Reply immediately.","You ignored us."],["Why no reply?","Just checking whether you had a chance to review our quotation.","Reply immediately.","You ignored us."],1),
  e("e07",3,"vocabulary","specification 指什么？","What is a specification?",["技术规格","销售佣金","汇率","保险费"],["technical requirements","sales commission","exchange rate","insurance premium"],0),
  e("e08",3,"grammar","填空：The samples ___ tomorrow.","Complete: The samples ___ tomorrow.",["will ship","will be shipped","shipped","are ship"],["will ship","will be shipped","shipped","are ship"],1),
  e("e09",4,"communication","如何专业地说明价格不含运费？","How do you state that freight is excluded?",["Freight no.","The quoted price excludes freight charges.","You pay all.","Shipping is yours."],["Freight no.","The quoted price excludes freight charges.","You pay all.","Shipping is yours."],1),
  e("e10",4,"vocabulary","counteroffer 是什么？","What is a counteroffer?",["还盘","形式发票","订单确认","报关"],["a revised offer in response","proforma invoice","order confirmation","customs declaration"],0),
  e("e11",4,"grammar","哪句语气最专业？","Which sentence has the most professional tone?",["Your price is too high.","There appears to be a gap between your price and our target.","Impossible price.","Cut it by 20%."],["Your price is too high.","There appears to be a gap between your price and our target.","Impossible price.","Cut it by 20%."],1),
  e("e12",5,"communication","电话中没听清型号，应该怎么说？","How do you clarify a model number on a call?",["What?","Could you repeat the model number and spell it out, please?","Speak clearly.","Send later."],["What?","Could you repeat the model number and spell it out, please?","Speak clearly.","Send later."],1),
  e("e13",5,"vocabulary","non-conformity 在质检中指什么？","What is a non-conformity?",["不符合要求项","免检产品","附加订单","预付款"],["failure to meet a requirement","inspection exemption","additional order","advance payment"],0),
  e("e14",5,"grammar","选择正确表达。","Choose the correct expression.",["We look forward to hear from you.","We look forward to hearing from you.","We look forward hear you.","We are look forward hearing."],["We look forward to hear from you.","We look forward to hearing from you.","We look forward hear you.","We are look forward hearing."],1),
  e("e15",6,"communication","客户投诉延迟，最佳开场是什么？","Best opening for a delay complaint?",["It is not our fault.","We understand the impact of the delay and apologize for the disruption.","Please wait.","The forwarder caused it."],["It is not our fault.","We understand the impact of the delay and apologize for the disruption.","Please wait.","The forwarder caused it."],1),
  e("e16",6,"vocabulary","root cause 与 symptom 的区别是什么？","How does a root cause differ from a symptom?",["根因导致问题，症状是表面表现","两者相同","症状导致根因","只用于财务"],["cause creates the issue; symptom is its visible effect","they are identical","symptom creates the cause","finance terms only"],0),
  e("e17",6,"grammar","哪句正确表达与事实相反的过去假设？","Which is a correct past unreal conditional?",["If we knew earlier, we act.","If we had known earlier, we would have adjusted production.","If we know, we would adjusted.","Had know, we adjust."],["If we knew earlier, we act.","If we had known earlier, we would have adjusted production.","If we know, we would adjusted.","Had know, we adjust."],1),
  e("e18",7,"communication","如何既拒绝降价又推进谈判？","How do you reject a discount while advancing negotiation?",["No discount.","While we cannot meet that price, we can review volume-based terms or payment structure.","Take it or leave it.","Your target is unreasonable."],["No discount.","While we cannot meet that price, we can review volume-based terms or payment structure.","Take it or leave it.","Your target is unreasonable."],1),
  e("e19",7,"vocabulary","commercially viable 的含义是？","What does commercially viable mean?",["商业上可行且可持续","技术上最先进","完全免税","无需合同"],["financially practical and sustainable","technically newest","fully tax-free","requiring no contract"],0),
  e("e20",7,"grammar","哪个句子使用 hedging 降低语气强度？","Which sentence uses hedging?",["You are wrong.","It may be worth reconsidering the delivery assumption.","Change the plan.","This will fail."],["You are wrong.","It may be worth reconsidering the delivery assumption.","Change the plan.","This will fail."],1),
  e("e21",8,"communication","会议中如何总结共识并锁定下一步？","How do you summarize agreement and secure next steps?",["Okay, bye.","To recap, we agreed on the revised specification; I will send the sample plan by Friday.","We discussed many things.","Let us see."],["Okay, bye.","To recap, we agreed on the revised specification; I will send the sample plan by Friday.","We discussed many things.","Let us see."],1),
  e("e22",8,"vocabulary","material adverse effect 指什么？","What is a material adverse effect?",["重大不利影响","原材料折扣","轻微包装变化","市场推广"],["a significant negative impact","raw-material discount","minor packaging change","marketing activity"],0),
  e("e23",9,"grammar","选择最清晰的合同式表达。","Choose the clearest contractual wording.",["Maybe seller fixes defects.","The Seller shall remedy verified defects within ten business days of notice.","Seller can fix sometime.","Defects should probably be handled."],["Maybe seller fixes defects.","The Seller shall remedy verified defects within ten business days of notice.","Seller can fix sometime.","Defects should probably be handled."],1),
  e("e24",9,"communication","如何用外交语气指出客户数据不一致？","How do you diplomatically flag inconsistent customer data?",["Your data is wrong.","We noticed a discrepancy between the forecast and the purchase order; could we reconcile the figures together?","Fix your numbers.","This makes no sense."],["Your data is wrong.","We noticed a discrepancy between the forecast and the purchase order; could we reconcile the figures together?","Fix your numbers.","This makes no sense."],1),
  e("e25",10,"communication","复杂谈判中哪句话同时包含立场、依据和交换条件？","Which statement contains position, rationale and a trade-off?",["We need 30% deposit.","To secure raw materials and hold the delivery slot, we require a 30% deposit; in return, we can guarantee the agreed lead time.","Pay first.","Our policy cannot change."],["We need 30% deposit.","To secure raw materials and hold the delivery slot, we require a 30% deposit; in return, we can guarantee the agreed lead time.","Pay first.","Our policy cannot change."],1),

  t("t01",1,"process","收到新询盘后，第一步应该是什么？","What is the first step after a new inquiry?",["立刻报最低价","确认客户、需求和关键规格","马上生产","发送合同"],["quote the lowest price","qualify buyer, needs and key specifications","start production","send a contract"],1),
  t("t02",1,"process","PI 通常指什么？","What does PI usually mean?",["形式发票","装箱单","检验证书","付款通知"],["proforma invoice","packing list","inspection certificate","payment notice"],0),
  t("t03",2,"process","FOB 条件下通常由谁安排主要运输？","Who normally arranges main carriage under FOB?",["卖方","买方","海关","银行"],["seller","buyer","customs","bank"],1),
  t("t04",2,"risk","预付款对卖方的主要好处是什么？","Main benefit of advance payment to the seller?",["降低收款风险","降低关税","免除质检","缩短运输距离"],["lower payment risk","lower duty","no inspection","shorter route"],0),
  t("t05",2,"process","HS Code 主要用于什么？","What is an HS Code mainly used for?",["商品海关分类","客户信用评分","汇率计算","邮件追踪"],["customs classification","buyer credit rating","FX calculation","email tracking"],0),
  t("t06",3,"process","报价前缺少年采购量，应如何处理？","Annual volume is missing before quotation. What should you do?",["随便估算","询问预计年用量和单次订单量","拒绝客户","只报样品价"],["guess","ask annual demand and order quantity","reject buyer","quote sample only"],1),
  t("t07",3,"risk","Net 60 最直接增加什么风险？","What risk does Net 60 directly increase?",["买方信用和现金流风险","包装风险","技术风险","商标风险"],["buyer credit and cash-flow risk","packaging risk","technical risk","trademark risk"],0),
  t("t08",3,"process","提单的核心作用之一是什么？","One core function of a bill of lading?",["运输收据与物权凭证","产品保修卡","报价批准","汇率锁定"],["transport receipt and title document","warranty card","quotation approval","FX hedge"],0),
  t("t09",4,"risk","信用证中的不符点可能导致什么？","What can an L/C discrepancy cause?",["银行拒付或延迟付款","自动涨价","免税","客户增加订单"],["refusal or delay of payment","automatic price rise","tax exemption","larger order"],0),
  t("t10",4,"process","CIF 报价通常包含什么？","What is normally included in CIF?",["成本、保险和运费","仅货值","关税和进口清关","目的地仓储"],["cost, insurance and freight","goods only","duty and import clearance","destination storage"],0),
  t("t11",4,"negotiation","客户要求降价，合理回应顺序是什么？","Best sequence for a discount request?",["立刻同意","澄清目标与数量，再交换条件","直接拒绝","停止回复"],["agree immediately","clarify target and volume, then trade concessions","reject directly","stop replying"],1),
  t("t12",5,"process","样品获批后，量产前最需要确认什么？","After sample approval, what must be confirmed before mass production?",["最终规格、数量、交期和付款条件","客户生日","竞争对手价格","社媒账号"],["final specs, quantity, lead time and payment","buyer birthday","competitor price","social account"],0),
  t("t13",5,"risk","处理客诉时 containment action 是什么？","What is a containment action in a claim?",["先控制问题继续扩散的临时措施","永久根因方案","价格谈判","年度审计"],["temporary action to stop further impact","permanent root-cause fix","price negotiation","annual audit"],0),
  t("t14",5,"process","出口报关资料不一致时应优先做什么？","What first when export documents conflict?",["按原样提交","核对合同、发票、箱单和申报要素","删除资料","让客户承担"],["submit anyway","reconcile contract, invoice, packing list and declaration","delete records","blame buyer"],1),
  t("t15",6,"risk","选择海外代理前最重要的尽调内容是什么？","Most important due diligence for an overseas agent?",["资信、渠道能力、合规与利益冲突","办公桌颜色","社交媒体粉丝","名片设计"],["credit, channel capability, compliance and conflicts","desk color","followers","business-card design"],0),
  t("t16",6,"negotiation","BATNA 在谈判中是什么？","What is BATNA?",["谈判破裂后的最佳替代方案","最低售价","银行手续费","年度预算"],["best alternative if no agreement","lowest price","bank fee","annual budget"],0),
  t("t17",6,"risk","产品进入欧盟市场前为何要确认合规责任？","Why confirm compliance responsibility before EU entry?",["避免认证、标签和责任风险","降低邮件数量","替代销售合同","免除物流"],["manage certification, labeling and liability risk","reduce emails","replace contract","avoid logistics"],0),
  t("t18",7,"process","客户预测与实际订单差异很大，应如何管理？","How should a large forecast-order gap be managed?",["继续盲目备货","建立滚动预测、冻结窗口和库存责任规则","取消客户","永久涨价"],["keep stocking blindly","use rolling forecast, frozen window and inventory liability","cancel buyer","raise price forever"],1),
  t("t19",7,"risk","汇率波动较大且订单周期长，可采取什么措施？","How can FX risk be managed on a long-cycle order?",["设报价有效期、币种条款或套期保值","忽略汇率","只接受口头承诺","延迟开票"],["quotation validity, currency clause or hedging","ignore FX","oral promise only","delay invoice"],0),
  t("t20",7,"negotiation","客户要求独家代理，首要谈判条件是什么？","Key condition for exclusivity?",["销量目标、区域、期限和退出机制","免费样品数量","邮件频率","展会礼品"],["sales target, territory, term and exit mechanism","free samples","email frequency","trade-show gifts"],0),
  t("t21",8,"risk","客户要求 DDP，但卖方不了解进口国税务，最大问题是什么？","Biggest concern when accepting DDP without local tax knowledge?",["进口清关、税费和主体资格风险","包装颜色","生产效率","品牌字体"],["import clearance, tax and importer-of-record risk","packaging color","production efficiency","brand font"],0),
  t("t22",8,"negotiation","重大质量索赔的专业解决框架是什么？","Professional framework for a major quality claim?",["事实与证据、责任分析、短期控制、根因纠正、商业方案","立即全额退款","否认责任","交给货代"],["facts, liability, containment, root-cause correction and commercial resolution","instant full refund","deny liability","hand to forwarder"],0),
  t("t23",9,"risk","制裁与出口管制筛查至少应覆盖什么？","What should sanctions/export-control screening cover?",["客户、最终用户、用途、目的地和受控物项","只查客户名字","只查付款银行","只查产品价格"],["buyer, end user, end use, destination and controlled items","buyer name only","bank only","price only"],0),
  t("t24",9,"negotiation","框架协议与单笔订单冲突时，最重要的是确认什么？","When a framework agreement conflicts with a PO, what matters most?",["文件优先顺序和特别条款效力","字体大小","邮件发送时间","业务员职级"],["order of precedence and effect of special terms","font size","email time","salesperson title"],0),
  t("t25",10,"risk","跨国项目同时存在延期、客户变更和成本上涨，应如何决策？","How should a cross-border project handle delay, scope change and cost escalation?",["建立证据时间线，量化影响，依据合同发出通知并提出可交换方案","继续执行不记录","只要求涨价","停止沟通"],["build evidence timeline, quantify impact, issue contractual notices and propose trade-offs","continue without records","only demand price rise","stop communicating"],0),
];
